test("prueba1 Fibonacci", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 0;
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});


test("prueba2 Fibonacci", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 2;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba3 Fibonacci", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 13;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.retroceder();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba4 Fibonacci", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 13;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.retroceder();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba5 FibonacciBinario", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 1101;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.retroceder();
  valorObtenido = objFibo.getValorBinario();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba6 FibonacciHexadecimal", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 2;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorHexadecimal();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba7 FibonacciHexadecimal", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = "d";
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.retroceder();
  valorObtenido = objFibo.getValorHexadecimal();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba8 FibonacciHexadecimal", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = "3db";
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorHexadecimal();
  ok(valorEsperado == valorObtenido, "Correcto");
});


test("prueba9 FibonacciBinario", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = "1111011011";
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorBinario();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba10 FibonacciRetroceder11", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 1;
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.avanzar();

  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba11 FibonacciRetroceder22yAvanzar", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 1;
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.avanzar();

  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba12 FibonacciReiniciaryAvanzar", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 1;
  objFibo.reiniciar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});


test("prueba13 FibonacciReiniciarRetrocederReiniciar", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 0;
  objFibo.reiniciar();
  objFibo.retroceder();
  objFibo.reiniciar();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba14 FibonacciRetroceder2VecesAvanzar2Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 1;
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.avanzar();
  objFibo.avanzar();

  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba15 FibonacciAvanzar5Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 5;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba16 FibonacciBinarioAvanzar5", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 101;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorBinario();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba17 FibonacciHexadecimalAvanzar5", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 5;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorHexadecimal();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba18 FibonacciHexadecimalAvanzar6", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = "8";
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorHexadecimal();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba19 FibonacciHexadecimalAvanzar12", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = "90";
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorHexadecimal();
  ok(valorEsperado == valorObtenido, "Correcto");
});


test("prueba20 FibonacciBinarioAvanzar12Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = "10010000";
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorBinario();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba21 FibonacciAvanzar24", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 46368;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();

  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba22 FibonacciAvanzar48", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 4807526976;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();


  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba23 FibonacciBinarioAvanzar48", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 100011110100011010000101001000000;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorBinario();
  ok(valorEsperado == valorObtenido, "Correcto");
});


test("prueba24 FibonacciAvanzar50Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 12586269025;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba25 FibonacciAvanzar52Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 32951280099;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba26 FibonacciAvanzar54", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 86267571272;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba27 FibonacciAvanzar58Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 591286729879;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba28 FibonacciHexadecimalAvanzar58Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = "89ab6f7c97";
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorHexadecimal();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba29 FibonacciBinarioAvanzar64Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 10011010011001100001110010100010000010111011;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorBinario();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba30 FibonacciAvanzar69Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 117669030460994;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});


test("prueba31 FibonacciBinarioAvanzar69Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 11010110000010011110100110000101111111001000010;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorBinario();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba32 FibonacciAvanzar74Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 1304969544928657;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba33 FibonacciAvanzar79Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 14472334024676221;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();

  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba34 FibonacciAvanzar90Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 2880067194370816120;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});


test("prueba35 FibonacciAvanzar100Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado=354224848179261915075;
  //valor que regresa 354224848179262000000
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba36 Fibonacci200Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 280571172992510140037611932413038677189525;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba37 FibonacciAvanzar200VecesReiniciar", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 0;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.reiniciar();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba38 FibonacciBinarioRetocederAvanzarRetrocederAvanzar", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 1;
  objFibo.retroceder();
  objFibo.avanzar();
  objFibo.retroceder();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorBinario();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba39 FibonacciHexadecimalRetocederAvanzarRetrocederAvanzar", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 1;
  objFibo.retroceder();
  objFibo.avanzar();
  objFibo.retroceder();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorHexadecimal();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba40 FibonacciHexadecimal50Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = "2ee333961";
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorHexadecimal();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba41 FibonacciHexadecimal90Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = "27f80ddaa1ba7878";
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorHexadecimal();
  ok(valorEsperado == valorObtenido, "Correcto");
});


test("prueba42 FibonacciBinarioAvanzar90Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = "‭10011111111000000011011101101010100001101110100111100001111000‬";
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorBinario();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba43 FibonacciBinarioAvanzar50Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 1011101110001100110011100101100001;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorBinario();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba44 FibonacciHexadecimalAvanzar50Veces", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = "2ee333961";
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorHexadecimal();
  ok(valorEsperado == valorObtenido, "Correcto");
});


test("prueba45 FibonacciRetroceder44avanzar1", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 1;
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.avanzar();

  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba46 FibonacciReiniciarAvanzar5Retroceder1Avanzar1", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 1;
  objFibo.reiniciar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.reiniciar();
  objFibo.retroceder();
  objFibo.avanzar();


  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba47 FibonacciAvanzar10Retroceder11Avanzar1", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 1;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.retroceder();
  objFibo.avanzar();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});


test("prueba48 FibonacciAvanzaRetrocedeAvanza", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 1;
  objFibo.avanzar();
  objFibo.retroceder();
  objFibo.avanzar();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba49 Fibonacci", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 610;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.retroceder();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba50 Fibonacci", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = 3;
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.retroceder();
  objFibo.avanzar();
  objFibo.retroceder();
  objFibo.avanzar();
  objFibo.retroceder();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.retroceder();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});


test("prueba51 FibonacciHexadecimal", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = "d";
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.retroceder();
  valorObtenido = objFibo.getValorHexadecimal();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba52 FibonacciHexadecimal", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = "3db";
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorHexadecimal();
  ok(valorEsperado == valorObtenido, "Correcto");
});


test("prueba53 FibonacciBinario", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = "1111011011";
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValorBinario();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba53 Padovan", function () {
  objPado = new NumeroPadovan();
  valorEsperado = 1;
  objPado.avanzar();
  valorObtenido = objPado.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba54 Padovan", function () {
  objPado = new NumeroPadovan();
  valorEsperado = 1;
  objPado.avanzar();
  objPado.avanzar();
  valorObtenido = objPado.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba55 Padovan", function () {
  objPado = new NumeroPadovan();
  valorEsperado = 2;
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  valorObtenido = objPado.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba56 Padovan", function () {
  objPado = new NumeroPadovan();
  valorEsperado = 2;
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  valorObtenido = objPado.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba57 Padovan", function () {
  objPado = new NumeroPadovan();
  valorEsperado = 2;
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  valorObtenido = objPado.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba58 Padovan", function () {
  objPado = new NumeroPadovan();
  valorEsperado = 3;
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  valorObtenido = objPado.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba59 Padovan", function () {
  objPado = new NumeroPadovan();
  valorEsperado = 37;
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  valorObtenido = objPado.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba60 Padovan", function () {
  objPado = new NumeroPadovan();
  valorEsperado = 5;
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.retroceder();
  valorObtenido = objPado.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba61 Padovan", function () {
  objPado = new NumeroPadovan();
  valorEsperado = 4;
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.retroceder();
  objPado.retroceder();
  valorObtenido = objPado.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba62 Padovan", function () {
  objPado = new NumeroPadovan();
  valorEsperado = 2;
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.avanzar();
  objPado.retroceder();
  objPado.retroceder();
  

  valorObtenido = objPado.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba63 Suerte", function () {
  objSu = new NumeroSuerte();
  valorEsperado = 3;
  objSu.avanzar(); 
  valorObtenido = objSu.getValor();
  ok(valorEsperado == valorObtenido, "correcto");
});

test("prueba64 Suerte", function () {
  objSu = new NumeroSuerte();
  valorEsperado = 15;
  objSu.avanzar(); 
  objSu.avanzar(); 
  objSu.avanzar(); 
  objSu.avanzar(); 
  objSu.avanzar(); 
  objSu.avanzar(); 
  objSu.avanzar(); 
  objSu.retroceder();
  objSu.retroceder();
  valorObtenido = objSu.getValor();
  ok(valorEsperado == valorObtenido, "correcto");
});

test("prueba65 FibonacciFeliz", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = false;
  objFibo.avanzar(); 
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.feliz(objFibo.getValor());
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba66 Ulam", function () {
  objFibo = new NumeroUlam();
  valorEsperado = 4;
  objFibo.avanzar(); 
  objFibo.avanzar();
  objFibo.avanzar();
  valorObtenido = objFibo.getValor();
  ok(valorEsperado == valorObtenido, "Correcto");
});

test("prueba67 CapicuaFibo", function () {
  objFibo = new NumeroFibonacci();
  valorEsperado = true;
  
  valorObtenido = objFibo.Capicua("161");
  ok(valorEsperado == valorObtenido, "Correcto");
});




